export const DRINKS_DATA_RESPONSE = 'DRINKS_DATA_RESPONSE';
export const DRINKS_RESET = 'DRINKS_RESET';

export const FILTERS_LIST_RESPONSE = 'FILTERS_LIST_RESPONSE';
export const FILTER_CHECKED = 'FILTER_CHECKED';
export const FILTERS_APPLIED = 'FILTERS_APPLIED';

export const PAGINATION_CURRENT_PAGE = 'PAGINATION_CURRENT_PAGE';
